#ifndef VALUES_INCLUDED
	#define VALUES_INCLUDED

	#define FPS 60

	#define ROWS 28

	#define GRID 10

	#define SHIPS 5

	#define BACKGROUND_COLOR 0

	#define TITLE_COLOR BACKGROUND_COLOR | FOREGROUND_BLUE | FOREGROUND_INTENSITY

	#define TEXT_COLOR BACKGROUND_COLOR | FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_RED

	#define LIGHT_TEXT_COLOR TEXT_COLOR | FOREGROUND_INTENSITY

	#define DARK_TEXT_COLOR BACKGROUND_COLOR | FOREGROUND_INTENSITY
#endif